//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qingjia_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Account
    {
        public string ID { get; set; }
        public string Psd { get; set; }
        public string RoleID { get; set; }
        public string Wechat { get; set; }
        public string Q1 { get; set; }
        public string A1 { get; set; }
        public string Q2 { get; set; }
        public string A2 { get; set; }
        public string Q3 { get; set; }
        public string A3 { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string YiBanID { get; set; }
        public string YB_AccessToken { get; set; }
    }
}
