//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qingjia_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Class
    {
        public string ID { get; set; }
        public string ClassName { get; set; }
        public string Grade { get; set; }
        public Nullable<int> Total { get; set; }
        public string TeacherID { get; set; }
        public string MonitorID { get; set; }
        public Nullable<System.Guid> Batch { get; set; }
    }
}
