//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qingjia_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Info
    {
        public string ID { get; set; }
        public string Grade { get; set; }
        public System.DateTime Deadline { get; set; }
        public string InfoOne { get; set; }
        public string InfoTwo { get; set; }
        public string InfoThree { get; set; }
        public string InfoFour { get; set; }
        public string InfoFive { get; set; }
        public string InfoSix { get; set; }
        public string InfoSeven { get; set; }
        public string InfoEight { get; set; }
        public string InfoNine { get; set; }
        public string InfoTen { get; set; }
    }
}
