//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qingjia_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LeaveList
    {
        public string ID { get; set; }
        public string StudentID { get; set; }
        public string Reason { get; set; }
        public System.DateTime SubmitTime { get; set; }
        public string StateLeave { get; set; }
        public string StateBack { get; set; }
        public string Notes { get; set; }
        public int TypeID { get; set; }
        public System.DateTime TimeLeave { get; set; }
        public Nullable<System.DateTime> TimeBack { get; set; }
        public string LeaveWay { get; set; }
        public string BackWay { get; set; }
        public string Address { get; set; }
        public Nullable<int> TypeChildID { get; set; }
        public string Lesson { get; set; }
        public string Teacher { get; set; }
        public string AuditTeacherID { get; set; }
        public Nullable<int> PrintTimes { get; set; }
    }
}
