//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qingjia_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LeaveIntership
    {
        public string ID { get; set; }
        public string StudentID { get; set; }
        public System.DateTime SubmitTime { get; set; }
        public string StateLeave { get; set; }
        public string StateBack { get; set; }
        public System.DateTime TimeLeave { get; set; }
        public System.DateTime TimeBack { get; set; }
        public string IntershipCompany { get; set; }
        public string IntershipAddress { get; set; }
        public string PrincipalName { get; set; }
        public string PrincipalTel { get; set; }
        public string Note { get; set; }
        public string Evidence1 { get; set; }
        public string Evidence2 { get; set; }
        public string Evidence3 { get; set; }
    }
}
