//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qingjia_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Student
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string ClassName { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string ContactOne { get; set; }
        public string OneTel { get; set; }
        public string ContactTwo { get; set; }
        public string TwoTel { get; set; }
        public string ContactThree { get; set; }
        public string ThreeTel { get; set; }
        public string Sex { get; set; }
        public string Room { get; set; }
    }
}
