//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qingjia_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Statistic
    {
        public string ID { get; set; }
        public Nullable<int> TotalNum { get; set; }
        public Nullable<int> VacationNum { get; set; }
        public Nullable<int> LongNum { get; set; }
        public Nullable<int> ShortNum { get; set; }
        public Nullable<int> NightNum { get; set; }
        public Nullable<int> SelfStudyNum { get; set; }
        public Nullable<int> ClassNum { get; set; }
    }
}
