//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qingjia_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudenBatch
    {
        public string ID { get; set; }
        public string StudentID { get; set; }
        public string ST_Name { get; set; }
        public string ST_Class { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string Reason { get; set; }
        public string TeacherID { get; set; }
        public string AuditState { get; set; }
        public Nullable<int> Batch { get; set; }
    }
}
