//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qingjia_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Student
    {
        public string ST_Num { get; set; }
        public string ST_Name { get; set; }
        public string ST_Tel { get; set; }
        public string ST_Email { get; set; }
        public string ST_QQ { get; set; }
        public string ContactOne { get; set; }
        public string OneTel { get; set; }
        public string ContactTwo { get; set; }
        public string TwoTel { get; set; }
        public string ContactThree { get; set; }
        public string ThreeTel { get; set; }
        public string ST_Sex { get; set; }
        public string ST_Dor { get; set; }
        public string ST_Class { get; set; }
        public string ST_Grade { get; set; }
        public string MonitorID { get; set; }
        public string ST_Teacher { get; set; }
        public string ST_TeacherID { get; set; }
    }
}
